# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 22:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('city', models.CharField(max_length=64, verbose_name='Cidade')),
                ('address', models.CharField(max_length=250, verbose_name='Endereço')),
                ('state', localflavor.br.models.BRStateField(max_length=2, verbose_name='Estado')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
                ('category', models.IntegerField(choices=[(1, 'Café'), (2, 'Restaurante'), (3, 'Coworking'), (4, 'Livraria'), (5, 'Outro')], default=1, verbose_name='Tipo')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.TextField()),
                ('drinks', models.TextField()),
                ('internet_password', models.CharField(max_length=50)),
                ('internet_open', models.IntegerField()),
                ('internet_rating', models.IntegerField()),
                ('customer_service', models.IntegerField()),
                ('price', models.IntegerField()),
                ('comfortable', models.IntegerField()),
                ('noise', models.IntegerField()),
                ('geral', models.IntegerField()),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluates', to='establishments.Establishment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
