# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 00:32
from __future__ import unicode_literals

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishmentevaluation',
            name='internet_open',
        ),
        migrations.AlterField(
            model_name='establishmentevaluation',
            name='comfortable',
            field=common.fields.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='establishmentevaluation',
            name='customer_service',
            field=common.fields.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='establishmentevaluation',
            name='drinks',
            field=models.TextField(verbose_name='Descreva os tipos de bebidas são servidos?'),
        ),
        migrations.AlterField(
            model_name='establishmentevaluation',
            name='foods',
            field=models.TextField(verbose_name='Descreva os tipos de comidas são servidos?'),
        ),
        migrations.AlterField(
            model_name='establishmentevaluation',
            name='geral',
            field=common.fields.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='establishmentevaluation',
            name='internet_password',
            field=models.CharField(max_length=50, verbose_name='Possui Internet?Ela possui senha?Qual?'),
        ),
        migrations.AlterField(
            model_name='establishmentevaluation',
            name='internet_rating',
            field=common.fields.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='establishmentevaluation',
            name='noise',
            field=common.fields.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='establishmentevaluation',
            name='price',
            field=common.fields.IntegerRangeField(),
        ),
    ]
